# ESPHome API für Home Assistant Integration
api:
  reboot_timeout: 0s
# Logger für serielle und ESPHome-Ausgabe aktivieren
logger:
  baud_rate: 115200
# Safe Mode Komponente für Button
safe_mode:
# =============================
# SSD1306 OLED Display
# =============================

# ...existing code...

# Am Ende der Datei einfügen:

# DiXY RDWC Controller - Zeltsensor VEREINFACHT (nur Basis-Hardware)
# 
# Diese Version hat nur die direkten Hardware-Sensoren OHNE komplexe Formeln
# Für Production: nutze diese Version zuerst zum Flashen
# Danach können Formeln über Home Assistant ergänzt werden
################################################################################
# DiXY RDWC Controller – Zeltsensor (Vereinfachtes Flash-Profil)
#
# Zweck:
# - Minimaler Satz an Sensoren (AS7341 + BMP280) damit erste Messwerte sofort
#   verfügbar sind.
# - Keine komplexen Berechnungen oder optionale Hardware, alles kann später in
#   Home Assistant ergänzt werden.
# - Ideal für das allererste Flashen eines neuen Zeltsensors.
################################################################################

substitutions:
  device_name: zeltsensor
  friendly_name: "Zeltsensor"
  device_description: "Spektral-Licht + Klima Monitoring"
  project_version: "0.1"
  
  # === PIN MAPPING ===

  # Pin Mapping
  i2c_sda_pin: "21"
  i2c_scl_pin: "22"
  
  # === I2C ADRESSEN ===

  # I2C Adressen
  as7341_address: "0x39"
  bmp280_address: "0x76"

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}
  comment: "DiXY Zeltsensor v0.1 – vereinfachte Flash-Version (nur Basis-Hardware)"
  project:
    name: "dixy.zeltsensor"
    version: ${project_version}


esp32:
  board: esp32dev
  framework:
    type: arduino

# Falls serielle Baudrate benötigt wird, im logger-Block angeben:
# logger:
#   baud_rate: 115200

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true            # verbindet ohne Scan (hilft bei verstecktem oder 5GHz/2.4GHz Dual-SSID)
  power_save_mode: none         # stabilere Verbindung
  ap:
    ssid: !secret zeltsensor_ap_ssid
    password: !secret zeltsensor_ap_password
i2c:
  sda: ${i2c_sda_pin}
  scl: ${i2c_scl_pin}
  frequency: 400kHz            # schnellerer Bus, damit AS7341 nicht blockiert

# ==============================================================================
# SENSOREN (Roh-Hardware)
# ==============================================================================
################################################################################
# Sensoren (nur direkte Hardware)
################################################################################
sensor:
  # BMP280 - Luftdruck
  # BMP280 – Luftdruck (Temperatur nur intern)
  - platform: bmp280_i2c
    temperature:
      name: "BMP280 Temperatur"
      id: bmp_temp
      internal: true
    pressure:
      name: "Luftdruck"
    address: ${bmp280_address}
    update_interval: 10s

  # AS7341 - Spektralsensor (11-Kanal)
  # AS7341 – Spektralsensor (11-Kanal)
  - platform: as7341
    address: ${as7341_address}
    atime: 29
    astep: 599
    gain: "X8"
    update_interval: 10s
    
    # Spektrale Kanäle (405-880nm)
    f1:
      name: "Violet (405nm)"
      id: violet
    f2:
      name: "Blue (430nm)"
      id: blue
    f3:
      name: "Green (470nm)"
      id: green
    f5:
      name: "Red (620nm)"
      id: red
    f8:
      name: "Near Infrared (880nm)"
      id: nir

  # WiFi Signal
  # WiFi Diagnostik
  - platform: wifi_signal
    name: "WiFi Signal"
    update_interval: 10s
  
  # Uptime

  - platform: uptime
    name: "Uptime"
    update_interval: 10s

# ===============================================================================
# TEMPLATE SENSORS (VPD)
# ===============================================================================
  # VPD (Vapour Pressure Deficit) – Template Sensor
  ##############################################################################
  # Template Sensoren – einfache Näherungen für Flash-Tests
  ##############################################################################
  - platform: template
    name: "VPD"
    id: vpd
    accuracy_decimals: 2
    update_interval: 10s
    lambda: |-
      // Dummy-Formel für VPD (kPa) – simuliert Wert zwischen 0.8 und 1.6
      static float v = 1.2;
      v += (float((rand() % 40) - 20)) / 100.0;
      if (v < 0.8) v = 0.8;
      if (v > 1.6) v = 1.6;
      return v;

  # PPFD (Photosynthetisch aktive Photonenflussdichte) – Template Sensor
  - platform: template
    name: "PPFD"
    id: ppfd
    accuracy_decimals: 0
    update_interval: 10s
    lambda: |-
      // Beispiel-Berechnung: PPFD aus AS7341-Kanälen (vereinfachte Formel)
      // Typisch: PPFD ≈ 0.5 * (red + blue + green)
      // Vereinfachte PPFD-Schätzung aus Rot/Blau/Grün
      if (id(red).has_state() && id(blue).has_state() && id(green).has_state()) {
        return 0.5f * (id(red).state + id(blue).state + id(green).state);
      } else {
        return NAN;
      }

  # DLI (Tageslichtintegral) – Template Sensor
  - platform: template
    name: "DLI"
    id: dli
    accuracy_decimals: 1
    update_interval: 10s
    lambda: |-
      // Beispiel-Berechnung: DLI aus PPFD (DLI = PPFD * 0.0864, für 24h)
      // DLI = PPFD * 0.0864 (vereinfachter 24h-Faktor)
      if (id(ppfd).has_state()) {
        return id(ppfd).state * 0.0864f; // 24h, für 12h: *0.0432
      } else {
        return NAN;
        return id(ppfd).state * 0.0864f;
      }

  # Lux – Template Sensor
  - platform: template
    name: "Lux"
    id: lux
    accuracy_decimals: 0
    update_interval: 10s
    lambda: |-
      // Beispiel-Berechnung: Lux aus AS7341-Kanälen (vereinfachte Formel)
      // Typisch: Lux ≈ 0.6 * green + 0.2 * red + 0.2 * blue
      // Näherung: 0.6*Grün + 0.2*Rot + 0.2*Blau
      if (id(green).has_state() && id(red).has_state() && id(blue).has_state()) {
        return 0.6f * id(green).state + 0.2f * id(red).state + 0.2f * id(blue).state;
      } else {
        return NAN;
      }
      return NAN;

# ==============================================================================
# TEXT SENSORS
# ==============================================================================
################################################################################
# Textsensoren
################################################################################
text_sensor:
  - platform: wifi_info
    ip_address:
      name: "WiFi SSID"
    mac_address:
      name: "MAC Adresse"
  

  - platform: version
    name: "ESPHome Version"
    hide_timestamp: false
  

  - platform: template
    name: "Project Version"
    lambda: 'return {"${project_version}"};'
    update_interval: never

# ==============================================================================
# BINARY SENSORS
# ==============================================================================
################################################################################
# Binary Sensoren
################################################################################
binary_sensor:
  - platform: status
    name: "Status"


# ==============================================================================
# BUTTONS
# ==============================================================================
################################################################################
# Buttons
################################################################################
button:
  - platform: restart
    name: "Restart"
  
  - platform: safe_mode
    name: "Safe Mode Boot"