esphome:
  name: simulation

esp32:
  board: esp32dev

wifi:
  ssid: "dixy"
  password: "monochrome1"

api:

logger:

sensor:
  - platform: template
    name: "Sim Temperatur"
    id: temp
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    update_interval: never

  - platform: template
    name: "Sim RLF"
    id: rlf
    unit_of_measurement: "%"
    accuracy_decimals: 1
    update_interval: never

  - platform: template
    name: "Sim Luftdruck"
    id: luftdruck
    unit_of_measurement: "hPa"
    accuracy_decimals: 1
    update_interval: never

  - platform: template
    name: "Sim EC"
    id: ec
    unit_of_measurement: "mS/cm"
    accuracy_decimals: 2
    update_interval: never

  - platform: template
    name: "Sim pH"
    id: ph
    unit_of_measurement: "pH"
    accuracy_decimals: 2
    update_interval: never

  - platform: template
    name: "Sim Wassertemperatur"
    id: wtemp
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    update_interval: never

interval:
  - interval: 10s
    then:
      - lambda: |-
          // Temperatur 20–28 °C
          id(temp).publish_state(20 + (rand() % 80) / 10.0);
          // RLF 45–65 %
          id(rlf).publish_state(45 + (rand() % 200) / 10.0);
          // Luftdruck 990–1030 hPa
          id(luftdruck).publish_state(990 + (rand() % 400) / 10.0);
          // EC 1.0–2.5 mS/cm
          id(ec).publish_state(1.0 + (rand() % 151) / 100.0);
          // pH 5.5–6.5
          id(ph).publish_state(5.5 + (rand() % 101) / 100.0);
          // Wassertemperatur 18–24 °C
          id(wtemp).publish_state(18 + (rand() % 60) / 10.0);