################################################################################
# DiXY RDWC Controller - Klimaknoten v0.2-beta
# 
# ⚠️  ALTERNATIVE CONFIG - NUR ALS BACKUP NUTZEN!
#
# Empfohlen: zeltsensor.yaml (primäre VPD-Regelung)
#
# Funktion: Standalone VPD-Regelung (separater ESP32 Node)
# Hardware: ESP32-DevKit
#
# GPIO PINOUT:
# ├─ I2C Bus (SDA=21, SCL=22):
# │  ├─ SHT31 (0x44): Lufttemperatur + Luftfeuchtigkeit
# │  ├─ MLX90614 (0x5A): IR-Blatttemperatur (kontaktlos)
# │  └─ BMP280 (0x76): Luftdruck + Höhe
# ├─ PWM Lüfter:
# │  └─ GPIO25: Abluft-Fan (0-100% LEDC)
# ├─ Relays (4-Kanal Modul):
# │  ├─ GPIO16: Relay 1 (Befeuchter)
# │  ├─ GPIO17: Relay 2 (Entfeuchter)
# │  ├─ GPIO18: Relay 3 (Heizung)
# │  └─ GPIO19: Relay 4 (Umluft-Fan)
# └─ Status LED:
#    └─ GPIO2: Onboard LED
################################################################################

substitutions:
  device_name: klimaknoten
  friendly_name: "Klimaknoten"
  device_description: "VPD-Regelung für RDWC-Zelt"
  project_version: "0.3-beta"

esphome:
  name: klimaknoten
  friendly_name: Klimaknoten
  comment: "DiXY Klimaknoten v0.2-beta – VPD-Regelung mit SHT31 + MLX90614 + WiFi Diagnostics + Health"

esp32:
  board: esp32dev
  framework:
    type: esp-idf

logger:
  level: INFO

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  
  ap:
    ssid: !secret klimaknoten_ap_ssid
    password: !secret klimaknoten_ap_password

api:
  reboot_timeout: 0s

ota:
  platform: esphome
  password: !secret klimaknoten_ota_password

web_server:
  port: 80

time:
  - platform: homeassistant
    id: ha_time

i2c:
  sda: 21
  scl: 22
  scan: true
  frequency: 400kHz

sensor:
  # SHT31 - Lufttemperatur + Luftfeuchte
  - platform: sht3xd
    temperature:
      name: "Lufttemperatur"
      id: air_temp
    humidity:
      name: "Luftfeuchte"
      id: air_humidity
    address: 0x44
    update_interval: 30s

  # MLX90614 - IR Blatttemperatur
  - platform: mlx90614
    name: "Blatttemperatur"
    id: leaf_temp
    address: 0x5A
    update_interval: 30s

  # BMP280 - Luftdruck
  - platform: bmp280
    temperature:
      name: "BMP280 Temperatur"
      internal: true
    pressure:
      name: "Luftdruck"
    address: 0x76
    update_interval: 30s

# ===== VPD-Berechnung (Home Assistant via Python) =====
# VPD = (SVP_leaf - SVP_air) * RH/100
# SVP = 0.6108 * e^((17.27 * T) / (T + 237.7))

output:
  # PWM für Abluft-Fan
  - platform: ledc
    pin: GPIO25
    frequency: 1000 Hz
    id: exhaust_fan_output

light:
  # Fan als Light für prozentuale Kontrolle
  - platform: monochromatic
    output: exhaust_fan_output
    name: "Abluft-Fan Speed"
    id: exhaust_fan_light

switch:
  # Befeuchter
  - platform: gpio
    pin: GPIO16
    name: "Befeuchter"
    id: humidifier
    restore_mode: ALWAYS_OFF

  # Entfeuchter
  - platform: gpio
    pin: GPIO17
    name: "Entfeuchter"
    id: dehumidifier
    restore_mode: ALWAYS_OFF

  # Heizung
  - platform: gpio
    pin: GPIO18
    name: "Heizung"
    id: heater
    restore_mode: ALWAYS_OFF

  # Umluft-Fan
  - platform: gpio
    pin: GPIO19
    name: "Umluft-Fan"
    id: circulation_fan
    restore_mode: ALWAYS_OFF
