esphome:
  name: zeltsensor
  friendly_name: "Zeltsensor"
  comment: "Minimalprofil BMP280 + AS7341"
  project:
    name: "loserat.dixy_zeltsensor"
    version: "0.1"

esp32:
  board: esp32dev
  framework:
    type: arduino

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "ZELTSENSOR_Fallback"
    password: "12345678"

ota:
  platform: esphome
  password: !secret zeltsensor_ota_password

i2c:
  sda: 21
  scl: 22
  scan: true

sensor:
  - platform: bmp280_i2c
    address: 0x76
    temperature:
      name: "BMP280 Temperatur"
    pressure:
      name: "BMP280 Luftdruck"
    update_interval: 60s

  - platform: as7341
    address: 0x39
    atime: 100
    astep: 999
    gain: X128

  # Simulierter DS18B20 (Dummy)
  - platform: template
    name: "DS18B20 Dummy"
    id: ds18b20_dummy
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    update_interval: 10s
    lambda: |-
      // Simulierter Wert zwischen 20 und 25°C
      static float t = 22.0f;
      t += (float((rand() % 20) - 10)) / 10.0f;
      if (t < 20.0f) t = 20.0f;
      if (t > 25.0f) t = 25.0f;
      return t;

  - platform: wifi_signal
    name: "ESP WiFi Signal"
    update_interval: 60s
  - platform: uptime
    name: "ESP Uptime"
    update_interval: 60s

logger:
api:

text_sensor:
  - platform: wifi_info
    ip_address:
      name: "ESP IP Adresse"
    ssid:
      name: "ESP WiFi SSID"
    bssid:
      name: "ESP WiFi BSSID"
    mac_address:
      name: "ESP MAC Adresse"


binary_sensor:
  - platform: status
    name: "ESP Status"

button:
  - platform: restart
    name: "ESP Restart"