# Minimalistische Simulationskonfiguration für DiXY Hydroknoten
esphome:
  name: hydroknoten-sim
  comment: "Simulationsknoten: sendet Dummy-pH, EC und Temperatur alle 20s"

esp32:
  board: esp32dev
  framework:
    type: arduino

logger:
  level: INFO

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "Hydroknoten SIM Fallback"
    password: "dixy12345"

api:
  encryption:
    key: "pKZmbcEqdXZygqLxWZjZ/Ot1qNey0ZvIq12qXscMBALa7uqRqavzjRouAF+rO7jR"

ota:
  platform: esphome
  password: "dixy"

sensor:
  - platform: template
    name: "Sim pH"
    id: sim_ph
    unit_of_measurement: "pH"
    accuracy_decimals: 2
    update_interval: 20s
    lambda: |-
      static float ph = 6.0;
      ph += (float((rand() % 20) - 10)) / 100.0;
      if (ph < 5.5) ph = 5.5;
      if (ph > 6.5) ph = 6.5;
      return ph;

  - platform: template
    name: "Sim EC"
    id: sim_ec
    unit_of_measurement: "mS/cm"
    accuracy_decimals: 2
    update_interval: 20s
    lambda: |-
      static float ec = 1.6;
      ec += (float((rand() % 16) - 8)) / 100.0;
      if (ec < 1.2) ec = 1.2;
      if (ec > 2.0) ec = 2.0;
      return ec;

  - platform: template
    name: "Sim Temperatur"
    id: sim_temp
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    update_interval: 20s
    lambda: |-
      static float t = 21.0;
      t += (float((rand() % 12) - 6)) / 10.0;
      if (t < 18.0) t = 18.0;
      if (t > 24.0) t = 24.0;
      return t;