################################################################################
# DiXY RDWC Hydroknoten v2 (ESPHome) - Minimal: Nur EC & pH über ADS1115
################################################################################

substitutions:
  device_name: hydroknoten-v2
  friendly_name: "Hydroknoten v2"
  project_name: "DiXY Hydroknoten v2"
  project_version: "0.1"
  i2c_sda_pin: "21"
  i2c_scl_pin: "22"
  ads1115_address: "0x48"

esphome:
  name: hydroknoten-v2
  comment: "Minimal: Nur EC & pH über ADS1115"
  project:
    name: "dixy.${project_name}"
    version: ${project_version}

esp32:
  board: esp32dev
  framework:
    type: arduino

logger:
  level: INFO

wifi:
  ssid: "dixy"
  password: "monochrome1"
  ap:
    ssid: "${friendly_name} Fallback"
    password: "dixy12345"

api:
  encryption:
    key: "VA/s0c7Bcl5wg03cgvaDw3DtWeREErZEGtti2ydeXzE="

ota:
  platform: esphome
  password: "dixy"

i2c:
  sda: ${i2c_sda_pin}
  scl: ${i2c_scl_pin}
  scan: true
  frequency: 400kHz
  id: bus_main

ads1115:
  - id: ads1
    address: ${ads1115_address}
    i2c_id: bus_main

sensor:
  - platform: ads1115
    ads1115_id: ads1
    name: "${friendly_name} EC Raw"
    id: ec_raw
    multiplexer: 'A0_GND'
    gain: 6.144
    update_interval: 10s
    filters:
      - median:
          window_size: 7
          send_every: 4
          send_first_at: 1

  - platform: ads1115
    ads1115_id: ads1
    name: "${friendly_name} pH Raw"
    id: ph_raw
    multiplexer: 'A1_GND'
    gain: 6.144
    update_interval: 10s
    filters:
      - median:
          window_size: 7
          send_every: 4
          send_first_at: 1
