esphome:
  name: hydroknoten
  comment: "Knoten für EC, pH, Temperatur, Außenluft. Für Hardware-Integration vorbereitet. Version 2.1"
  project:
    name: "loserat.dixy_hydroknoten"
    version: "2.1"
  platformio_options:
    board_build.flash_mode: "dio"
  on_boot:
    priority: -100.0
    then:
        - logger.log: "Hydroknoten gestartet. Version 2.1"

esp32:
  board: esp32dev
  framework:
    type: arduino

logger:
  level: INFO


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "Hydroknoten SIM Fallback"
    password: "dixy12345"
  # Info: SSID und Passwort werden aus secrets.yaml geladen
  # Alternativ können sie hier auch direkt eingetragen werden (nicht empfohlen).
  # ssid: "Dein_WLAN_SSID"
  # password: "Dein_WLAN_Passwort"

api:
  encryption:
    key: "zCy9bhBNViqsl/kfDQ2eNJW8hzYuGDLyTk250eYjWYY="
    # Hinweis: Key
    # - kann mit `esphome api encryption_key <dein_projekt>.yaml` generiert werden
    # - muss bei Änderung in Home Assistant neu eingetragen werden
    # - alternativ kann die Verschlüsselung auch deaktiviert werden (nicht empfohlen)

ota:
  platform: esphome
  password: "dixy"
# Hinweis: Passwort kann hier direkt eingetragen werden oder aus secrets.yaml geladen werden
# password: !secret hydroknoten_ota_password

web_server:
  port: 80

sensor:
  # --- Messwerte (aktuell simuliert, ohne Sim-Namen) ---
  - platform: template
    name: "Hydroknoten EC Sensor"
    id: sim_ec
    unit_of_measurement: "mS/cm"
    accuracy_decimals: 2
    update_interval: 20s
    lambda: |-
      static float ec = 1.6;
      ec += (float((rand() % 16) - 8)) / 100.0;
      if (ec < 1.2) ec = 1.2;
      if (ec > 2.0) ec = 2.0;
      return ec;
  - platform: template
    name: "Hydroknoten pH Sensor"
    id: sim_ph
    unit_of_measurement: "pH"
    accuracy_decimals: 2
    update_interval: 20s
    lambda: |-
      static float ph = 6.0;
      ph += (float((rand() % 20) - 10)) / 100.0;
      if (ph < 5.5) ph = 5.5;
      if (ph > 6.5) ph = 6.5;
      return ph;
  - platform: template
    name: "Hydroknoten Temperatur"
    id: sim_temp
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    update_interval: 20s
    lambda: |-
      static float t = 21.0;
      t += (float((rand() % 12) - 6)) / 10.0;
      if (t < 18.0) t = 18.0;
      if (t > 24.0) t = 24.0;
      return t;
  - platform: template
    name: "Hydroknoten Zelttemperatur außen"
    id: sim_tent_temp_outside
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    update_interval: 20s
    lambda: |-
      static float t = 17.0;
      t += (float((rand() % 10) - 5)) / 10.0;
      if (t < 15.0) t = 15.0;
      if (t > 20.0) t = 20.0;
      return t;


# --- Hardware vorbereitet ---
# --- Buttons vorbereitet ---

text_sensor:
  - platform: template
    name: "Hydroknoten Version"
    id: hydroknoten_version
    icon: "mdi:tag"
    lambda: |-
      return {"v2.1"};
    update_interval: 3600s
  - platform: wifi_info
    ip_address:
      name: "ESP IP Adresse"
    ssid:
      name: "ESP WiFi SSID"
    bssid:
      name: "ESP WiFi BSSID"
    mac_address:
      name: "ESP MAC Adresse"

# Beispiel für vier Buttons mit Pin-Mapping aus config.yaml:

binary_sensor:
  # --- Dummy-GPIO-Buttons für Home Assistant ---
  - platform: gpio
    pin:
      number: GPIO16
      mode: INPUT_PULLUP
    name: "EC Kalibrierung – Lösung 1"
    id: button_1
    internal: false
  - platform: gpio
    pin:
      number: GPIO17
      mode: INPUT_PULLUP
    name: "EC Kalibrierung – Lösung 2"
    id: button_2
    internal: false
  - platform: gpio
    pin:
      number: GPIO18
      mode: INPUT_PULLUP
    name: "pH Kalibrierung – Lösung 1"
    id: button_3
    internal: false
  - platform: gpio
    pin:
      number: GPIO19
      mode: INPUT_PULLUP
    name: "pH Kalibrierung – Lösung 2"
    id: button_4
    internal: false



